#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script creates a table ($unknowns) to hold unknown words, and fills it with unknown words tagged as $mylang in each file specified in the FILES line.

FILES=inputs/patagonia/beta/*.cha
unknowns=patagonia_cym_unknowns
mylang=cym
uniq=${unknowns}_uniq

php unknowns/create_unk_table.php $unknowns
php unknowns/create_unk_table.php $uniq

for f in $FILES
do
	echo "Processing $f ..."
	php unknowns/gather_unknowns.php $f $unknowns $mylang
done

export PGPASSWORD=kevindbs
psql="psql -h localhost -U kevin -d autoglosser"

$psql --c "insert into $uniq(surface) select surface from $unknowns group by surface order by surface"

$psql --c "alter table $uniq alter column filename type text"

export PGPASSWORD=
