#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

export PGPASSWORD=kevindbs
psql="psql -h localhost -U kevin -d autoglosser"

FILES=inputs/patagonia/beta/*.cha
COMBI=pat

for f in $FILES
do
	filename=$(basename $f)  # the filename from the path - file.cha
	fixedfile=${filename%.cha}_cgwords  # switch the filename's extension to _cgwords for the output file - file_cgwords
	echo "Processing $fixedfile ..."
	$psql --c "insert into combiwords_$COMBI(utterance_id, location, surface, auto, speaker, langid, filename) select utterance_id, location, surface, auto, speaker, langid, filename from $fixedfile"
done

# $psql here is not a mistake - it refers to the variable set up above.
$psql --c "create table combiwords_${COMBI}_uniq as select langid, surface, auto, count(surface) from combiwords_$COMBI where langid!='999' group by langid, surface, auto order by langid, surface, auto"

$psql --c "alter table combiwords_${COMBI}_uniq add column filename text"

export PGPASSWORD=
# remove the PG password again
