#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script converts two-letter tags (es, en) to three-letter tags (spa, eng).  Number tags can use the import_and_convert script instead.
#  Run as: sed_convert_es /path/to/file.cha
chafile=$1  # the argument to the script; = the full path to the file - path/to/file.cha
#echo $chafile
filename=$(basename $chafile)  # the filename from the path - file.cha
#echo $filename
path=$(dirname $chafile)  # the path to the file - path/to
#echo $path
fixedfile=${filename}.txt  # set up an output file
#echo $fixedfile
sed -e 's/@s:en\&es+en\([ >]\)/@s:eng\&spa+eng\1/g' < $chafile | \
sed -e 's/@s:en\&es\([ >]\)/@s:eng\&spa\1/g' | \
sed -e 's/@s:en+es\([ >]\)/@s:eng+spa\1/g' | \
sed -e 's/@s:es+en\([ >]\)/@s:spa+eng\1/g' | \
sed -e 's/@s:en\([ >]\)/@s:eng\1/g' | \
sed -e 's/@s:es\([ >]\)/@s:spa\1/g' > $path/$fixedfile  # output to the path + new filename
mv $path/$fixedfile $path/$filename  # replace the original file with the fixed file, giving a fixed .cha file

# Also need to handle where @s is used without any language marker
# Need to extend to handle "en." instead of "en ."