#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script lifts out the chat file header.
chafile=$1  # the argument to the script; = the full path to the file - path/to/file.cha
#echo $chafile
filename=$(basename $chafile)  # the filename from the path - file.cha
#echo $filename
path=$(dirname $chafile)  # the path to the file - path/to
#echo $path
# Lowercase the extensionless version of the filename
shortfile=`echo ${filename%.cha} | tr A-Z a-z`
#echo $shortfile
# Collect the header lines down to and including the first speaker line, and then delete the speaker line
sed -n '1,/\*[A-Z]/'p  < $chafile | \
sed '/\*[A-Z]/ d' > $path/$shortfile.snip
# Create the outputs dir if it doesn't exist, and copy the headers there
mkdir -p outputs/$shortfile
mv $path/$shortfile.snip outputs/$shortfile/
