#!/bin/sh
# This script lifts out the chat file header.
chafile=$1  # the argument to the script; = the full path to the file - path/to/file.cha
#echo $chafile
filename=$(basename $chafile)  # the filename from the path - file.cha
#echo $filename
path=$(dirname $chafile)  # the path to the file - path/to
#echo $path
# Lowercase the extensionless version of the filename
shortfile=`echo ${filename%.cha} | tr A-Z a-z`
echo $shortfile
# Collect the header lines down to and including the first speaker line, and then delete the speaker line
sed -n '1,/\*[A-Z]/'p  < $chafile | \
sed '/\*[A-Z]/ d' > $path/$shortfile.header
# Create the outputs dir if it doesn't exist, and copy the headers there
mkdir -p outputs/$shortfile
mv $path/$shortfile.header outputs/$shortfile/
