#!/bin/sh
# Convert Microsoft Windows line-ends to spaces
# Required in order to have each line on one line without breaks
# Run fromdos myfile.cha first, to get rid of the \r from a Windows machine
sed -e 'N;s/\n\t/ /;P;D;' < ../inputs/Miami/zeledon9.cha | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' > ../inputs/Miami/zeledon9.txt

