#!/bin/sh

sed -e 'N;s/\n\t/ /;P;D;' < inputs/Patagonia1_headerless.cha | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' | \
sed -e 'N;s/\n\t/ /;P;D;' > inputs/Patagonia1.cha
