#!/bin/sh

sed -e 'N;s/\n\s\t//;P;D;' < new/UZ.txt | \
sed -e 'N;s/\n\s\t//;P;D;' | \
sed -e 'N;s/\n\s\t//;P;D;' | \
sed -e 'N;s/\n\s\t//;P;D;' | \
sed -e 's/\[.*\?\]//g' | \
sed -e "s/’/'/g" | \
sed -e "s/‘/'/g" | \
sed -e 's/–/-/g' | \
sed -e 's/‑/-/g' | \
sed -e 's/²//g' | \
sed -e 's/³//g' | \
sed -e 's/…/ ... /g' | \
sed -e '/^.*$/a\ ' > new/first.txt
