#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script adds an empty %eng tier after every speaker line not tagged with the precode [- eng].
FILES=inputs/patagonia/beta/spa/*.cha
for f in $FILES
do
# For mainly-Spanish files - add an empty %eng tier after every speaker line not tagged with the precode [- eng].
#echo "Processing $f ..."
	sed -i '/\*[A-Z]*:\o011[^\[]/ a\
%eng:\o011' $f
# Do NOT indent the above line - it is split from the previous one to add a newline; an additional indent will give a tab at the beginning of the line.
# For mainly-English files, we need two appends.
# The first adds an empty %eng tier after every speaker line tagged with the precode [- spa].
#	sed -i '/\*[A-Z]*:\o011\[/ a\
#%eng:\o011' $f
# The second adds an empty %eng tier after every speaker line containing a Spanish word.
#	sed -i '/@s:spa/ a\
#%eng:\o011' $f
# Do NOT indent the above line - it is split from the previous one to add a newline; an additional indent will give a tab at the beginning of the line.
# Where an empty %eng tier has been added before one which already exists (eg the file translation is partially complete), remove the empty %eng tier again:
	sed -i 'N;s/%eng:\o011\n\(%eng\)/\1/;P;D;' $f
# Remove the empty %eng tier where it consists solely of xxx or www or &= (eg &=laughs) ...
	sed -i 'N;s/\(\o011xxx \. .*\n\)%eng.*/\1/;P;D;' $f
	sed -i 'N;s/\(\o011www \. .*\n\)%eng.*/\1/;P;D;' $f
	sed -i 'N;s/\(\o011&=.*\n\)%eng.*/\1/;P;D;' $f
# ... and delete the empty line
	sed -i '/^$/ d' $f
done



























