#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script adds an %eng tier after every speaker line not tagged with the precode [- eng].  The line contains"vvv", so that the file will still pass CHECK.
# To remove %eng: vvv lines, run: sed -i '/^%eng:\tvvv$/ d' inputs/miami/beta/file.cha 

#FILES=inputs/miami/beta/spa/*.cha
#FILES=inputs/miami/beta/herring17.cha
FILES=inputs/patagonia/beta/patagonia21.cha

for f in $FILES
do
echo "Processing $f ..."

# For mainly-Spanish files (spa, eng) - append (a) an %eng tier after every speaker line NOT tagged with the precode [- eng].
	sed -i '/\*[A-Z]*:\o011[^[]/ a\
%eng:\o011vvv' $f
# Do NOT indent the above line - it is split from the previous one to add a newline; an additional indent will give a tab at the beginning of the line.
# Remove %eng tiers where the line includes [- eng] after continuation markers.
	sed -i 'N;s/\(\*[A-Z]*:\o011+[<^+,"] \[.*\n\)%eng:\o011vvv/\1/;P;D;' $f

# # For mainly-English files (eng, spa), we need three appends.
# # The first adds an %eng tier after every speaker line tagged with the precode [- spa].
# 	sed -i '/\*[A-Z]*:\o011\[/ a\
# %eng:\o011vvv' $f
# # The second adds an %eng tier after every speaker line tagged with the precode [- spa], preceded by continuation markers.
# 	sed -i '/\*[A-Z]*:\o011+[<^+,"] \[/ a\
# %eng:\o011vvv' $f
# # The third adds an %eng tier after every speaker line containing a Spanish word.
# 	sed -i '/@s:spa/ a\
# %eng:\o011vvv' $f
# # Do NOT indent the above lines - they are split from the previous one to add a newline; an additional indent will give a tab at the beginning of each line.

# Remove (old) blank %eng lines if they exist, and then remove a vvv %eng tier which has been added before one which already exists (eg the file translation is partially complete), or a vvv %eng tier added after a Comment line:
	sed -i '/%eng:\o011$/ d' $f
	sed -i 'N;s/%eng:\o011vvv\n\(%eng\)/\1/;P;D;' $f
	sed -i 'N;s/\(@Comment.*\n\)%eng:\o011vvv/\1/;P;D;' $f

# Remove the %eng tier where the speaker tier consists solely of xxx ...
	sed -i 'N;s/\(\o011xxx \. .*\n\)%eng.*/\1/;P;D;' $f
	sed -i 'N;s/\(\o011+[<^+,"] xxx \. .*\n\)%eng.*/\1/;P;D;' $f
# ... or www ...
	sed -i 'N;s/\(\o011www \. .*\n\)%eng.*/\1/;P;D;' $f
	sed -i 'N;s/\(\o011+[<^+,"] www \. .*\n\)%eng.*/\1/;P;D;' $f
# ...or &= (eg &=laughs ...
	sed -i 'N;s/\(\o011&=.*\n\)%eng.*/\1/;P;D;' $f
	sed -i 'N;s/\(\o011+[<^+,"] &=.*\n\)%eng.*/\1/;P;D;' $f

# ... and delete any empty lines
	sed -i '/^$/ d' $f
	
done
