#!/bin/sh
# This script collects the autoglossed files specified in the FILES line and copies renamed versions into the collected folder
FILES=inputs/siarad/beta/*.cha
for f in $FILES
do
	echo "Processing $f ..."
	# take action on each file
	filename=$(basename $f)
	fixedfile=${filename%.cha}
	echo $fixedfile
	cp outputs/$fixedfile/${fixedfile}_autoglossed.txt collected/$filename
done