#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script changes the extension of the chat files in a specified directory from .cha to .txt

FILES=siarad_web/*.cha

for f in $FILES
do
	filename=$(basename $f)  # the filename from the path - file.cha
	path=$(dirname $f)  # the path to the file - path/to
	fixedfile=${filename%.cha}.txt  # switch the filename's extension to .txt for the output file - file.txt
	echo "Processing $filename ..."
	mv $path/$fixedfile $path/$filename  # replace the original file with the fixed file, giving a fixed .cha file
done

















