#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script collects the sample clauses from the files specified in the FILES line and combines them into one file in the collected folder
# Create the empty file first.
FILES=inputs/siarad/beta/*.cha
for f in $FILES
do
	echo "Processing $f ..."
	# take action on each file
	filename=$(basename $f)
	fixedfile=${filename%.cha}
	# echo $fixedfile
	cat outputs/$fixedfile/${fixedfile}_clauses.csv >> collected/all_sampleclauses.csv
done