#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script collects the autoglossed files specified in the FILES line and copies renamed versions into the collected folder
FILES=inputs/miami/beta/spa/*cha
#FILES=outputs/siarad_manual/pdfs/*.pdf
REPO=inputs/miami
for f in $FILES
do
	echo "Processing $f ..."
	filename=$(basename $f)
	fixedfile=${filename%.cha}
	#cp inputs/miami/spa/${fixedfile}.pdf inputs/miami/spa/pdfs/
	cp outputs/$fixedfile/${fixedfile}.pdf $REPO/pdfs
	#cp inputs/miami/spa/${fixedfile}.cha inputs/miami/spa/chats/${fixedfile}.txt
	#mv outputs/siarad_manual/pdfs/$filename outputs/siarad_manual/pdfs/pdfs/
done