#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# WARNING
# This script deletes autoglosser tables from the database - use with care! If you want to retain the tables, archive them first using utils/sh_global_dump_corpus - you can then reinstall them by using utils/sh_global_update_corpus.
# WARNING

export PGPASSWORD="kevindbs"
psql="psql -h localhost -U kevin -d autoglosser"

corpus="patagonia"
dbname="sox"

#FILES="herring1 herring10 herring7 herring9 sastre1 zeledon1"  # Individual table names.
FILES=inputs/$corpus/beta/*.cha  # Corpus tables, based on the chat files in the corpus directory.

for f in $FILES
do
	filename=$(basename $f)  # the filename from the path - file.cha
	chat=${filename%.cha}  # drop the filename's extension
	
	echo "Processing $chat ..."
		
	#$psql -c "drop table if exists ${chat}_cgutterances"
	#$psql -c "drop table if exists ${chat}_cgwords"
	#$psql -c "drop table if exists ${chat}_cgfinished"
	#$psql -c "drop table if exists ${chat}_trans"
	$psql -c "drop table if exists ${chat}_${dbname}"

done

export PGPASSWORD=
# remove the PG password again
