#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script fixes instances where the precode is mistakenly placed before the continuation markers.

#FILES=inputs/patagonia/beta/*.cha
#FILES="inputs/miami/alpha/023/herring1.cha inputs/miami/alpha/023/herring2.cha inputs/miami/alpha/023/herring12.cha" 
FILES="inputs/miami/beta/zeledon1.cha"

for f in $FILES
do
	echo "Processing $f ..."
	sed -i 's/\(\[- \(cym\|eng\|spa\)\]\) \(+[<^+,"]\)/\3 \1/g' $f
	# Note in the above that the bar has to be escaped on the regex part.
	# Note also that there are THREE backreference groups, counting from left to right - we need to swap the positions of the third (the continuation marker) with the first (the precode - which contains the second, the langid).
done



























