#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script does a compressed dump of the _cgutterances and _cgwords table for each file in the corpus into a dump dir.
# The --clean option means that the file will include SQL commands to drop the old table.

FILES="patagonia1 patagonia2 patagonia3 patagonia6 patagonia9"  # Patagonia
#FILES="herring1 herring10 herring7 herring9 sastre1 zeledon1"  # Miami
#FILES=inputs/siarad/beta/*.cha  # Siarad
for f in $FILES
do
	filename=$(basename $f)  # the filename from the path - file.cha
	chat=${filename%.cha}  # drop the filename's extension
	echo "Processing $chat ..."
	pg_dump -t ${chat}_cgutterances --clean autoglosser | gzip > dbdevel/patagonia_dump_gz/${chat}_cgutterances.sql.gz
	pg_dump -t ${chat}_cgwords --clean autoglosser | gzip > dbdevel/patagonia_dump_gz/${chat}_cgwords.sql.gz
done
