#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script imports compressed dumps of _cgutterances and _cgwords tables.
# NOTE:  If the table fails to import (perhaps with feedback like this:
#		invalid command \N
#		ERROR:  syntax error at or near "6"
#		LINE 1: 6 1 6 . 
# check that the old table you are replacing has no dependencies, for instance: views that depend on it.
# If so, you will first need to drop the old table manually:
# 		psql -U username -d database (and enter password)
#		drop table mytable cascade;
#		\q

export PGPASSWORD="kevindbs"
psql="psql -h localhost -U kevin -d miami"

#FILES=dbdevel/miami_dump/*_cgwords.sql.gz
FILES=dbdevel/mc_dump/*.sql.gz

for f in $FILES
do
        echo "Processing $f ..."
        gunzip -c $f | $psql
done

export PGPASSWORD=
# remove the PG password again














