#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script uses perl to fix all instances of a particular string in all the files in the corpus.  Sed is also a (slightly faster) option, but the drawback is that it's regex implementation is not the standard PCRE one.
FILES=inputs/patagonia/beta/*.cha

for f in $FILES
do
	#sed -i "/\*[A-Z]/s/ar \(\(draws|goll\)\) /ar_\1 /g" $f
	#sed -i "/\*[A-Z]/s/\([[:space:]]\)oh /\1o@s:cym\&spa /g" $f
	#sed -i "/\*[A-Z]/s/\([ <]\)neud/\1wneud/g" $f 
	#sed -i "/\*[A-Z]/s/ i \([mf]\)ewn/ i_\1ewn/g" $f 
	#perl -pi -e 's/([[:blank:]])i ((ffwrdd|fynylawr|gyd)) /\1i_\2 /g' $f
	#perl -pi -e 's/([[:blank:]]yn) ((ystod) )/\1_\2/g' $f
	perl -pi -e 's/([[:blank:]])hanodd /\1&h anodd /g' $f
done



























