#!/bin/sh

#/* 
#*********************************************************************
#Copyright Kevin Donnelly 2010, 2011.
#kevindonnelly.org.uk
#This file is part of the Bangor Autoglosser.
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License and the GNU
#Affero General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option)
#any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#and the GNU Affero General Public License along with this program.
#If not, see <http://www.gnu.org/licenses/>.
#*********************************************************************
#*/ 

# This script changes the autoglossed files in a particular corpus to allow them to fit in with Talkbank conventions, and puts them in a new folder - "submitted_to_Talkbank".

corpus=patagonia
AUTO=inputs/$corpus/autoglossed
TBPATH=inputs/$corpus/submitted_to_Talkbank
FILES=$TBPATH/*.cha

# Remove the existing folder, recreate it, and copy in the files.
rm -rf $TBPATH
mkdir $TBPATH
cp $AUTO/*.cha $TBPATH/

for f in $FILES
do
	echo "Processing $f ..."

	# Change %aut to %xaut.
	sed -ri "s/%aut/%xaut/g" $f

	# In the @Media header, convert number < 10 to two digits.
	sed -ri '/@Media/s/([0-9],)/0\1/g' $f
	
	# Rename files where number < 10.
	filename=$(basename $f)
	shortname=${filename%.cha}
	#echo $shortname
	fixedname=$(echo $shortname | sed -r 's/([a-z])([0-9])$/\10\2/')
	#echo $fixedname
	# Remove "patagonia" from filenames.
	fixedname=$(echo $shortname | sed -r 's/patagonia//')
	# Use /dev/null to suppress messages from mv saying the two names are the same.
	mv $f $TBPATH/$fixedname.cha 2>/dev/null

done