#!/bin/sh
# This script runs import_and_convert on all the files specified in the FILES line
FILES=inputs/siarad/alpha/*.cha
for f in $FILES
do
	echo "Processing $f ..."
	# take action on each file
	php import_and_convert.php $f
done
