#!/bin/sh
# This script selects a sample of utterances in each file specified in the FILES line, and splits them into clauses
FILES=inputs/siarad/beta/*.cha
for f in $FILES
do
	echo "Processing $f ..."
	# take action on each file
	php clauses/split_clauses.php $f
done
